#!/bin/sh

# Copyright (c) 2013, Aaron Fineman <abyxcos@mnetic.ch>
#
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all
# copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS
# ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
# WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE
# USE OR PERFORMANCE OF THIS SOFTWARE.

## Config file
. ./smallblog.conf			# Default conf file

## HTML templates
blog_header="
<!-- HTML generated by smallblog <https://github.com/abyxcos/smallblog> -->
<!DOCTYPE html>
<html>
<head>
  <title>%TITLE%</title>
  <link rel=\"stylesheet\" href=\"${PREFIX}/main.css\">
  <link rel=\"stylesheet\" href=\"${PREFIX}/local.css\">
  <link rel=\"stylesheet\" href=\"main.css\">
  <link rel=\"stylesheet\" href=\"local.css\">
</head>
<body>
  <div class=\"container\">
  <div class=\"site\">
    <div class=\"header\">
      <h1 class=\"title\"><a href=\"${PREFIX}\">${title}</a></h1>
      <a class=\"extra\" href=\"${PREFIX}/archive.html\">all posts</a>
      ${menu}
    </div>"
blog_footer="
    <div class=\"footer\"><p />
      <div class=\"contact\">
        ${name}<br />
        ${footer2_text}
      </div>
      <div class=\"contact\">
        <a href=\"mailto:${email}\">${email}</a><br />
        <a href=\"${footer2_link}\">${footer2_link}</a>
      </div>
    </div>
  </div>
  </div>
</body>
</html>"

## Supporting functions
# make_post filename.md
make_post(){
	_title=`head -n1 $1 | sed 's/^#* //'`
	_date=${1%/*}

	echo "<h1 class=\"title\"><a href='${PREFIX}/$1.html'>${_title}</a></h1>"
	echo "<p class=\"meta\">Date: ${_date//\//-}</p>"
	echo "<div class=\"post\">"
	tail -n +2 "$1" | markdown | sed 's/^<p>tags: /<p class=\"meta\">tags: /'
	echo "</div><br/>"
	echo ""
}

# make_index folder title
make_index(){
	echo "${blog_header/\%TITLE\%/$2}"
	echo "<h2>$2:</h2>"
	echo "<ul class=\"posts\">"

	# Sort by time and dereference symmlinks
	for post in `ls -Ht ${1}/*.md`; do
		_title=`head -n 1 "${post}" | sed 's/#* //'`

		echo "<li><span>${post%/*}</span> &raquo; <a href=\"${PREFIX}/${post}.html\">${_title}</a></li>"
	done

	echo "</ul>"
	echo "${blog_footer}"
}

# make_date_index folder title
make_date_index(){
	echo "${blog_header/\%TITLE\%/$2}"
	echo "<h2>$2:</h2>"
	echo "<ul class=\"posts\">"

	for post in `ls -r ${1}/*.md`; do
		_title=`head -n 1 "${post}" | sed 's/#* //'`
		_time=${post%/*}
		_month=`echo ${_time} | cut -d/ -f2`

		if [ "${_oldmonth-"00"}" != "${_month}" ]; then
			_oldmonth="${_month}"
			echo "<h3>${_time%%/*} - ${_month}:</h3>"
		fi

		echo "<li><span>${_time//\//-}</span> &raquo; <a href=\"${PREFIX}/${post}.html\">${_title}</a></li>"
	done

	echo "</ul>"
	echo "${blog_footer}"
}


## Start of the main logic
# Generate the individual posts
for post in `ls -r */*/*/*.md`; do
	_title=`head -n1 ${post} | sed 's/^#* //'`
	echo "${blog_header/\%TITLE\%/${_title}} `make_post "${post}"` ${blog_footer}" > "${post}.html"
done

# Generate the blog front page (index.html)
echo "" > index.html
echo "${blog_header/\%TITLE\%/${title}}" >> index.html
for post in `ls -r */*/*/*.md | head -n ${max_posts}`; do
	make_post "${post}" >> index.html
done
echo "<h3><a class=\"extra\" href=\"${PREFIX}/archive.html\">all posts</a></h3>" >> index.html
echo "${blog_footer}" >> index.html

# Generate the archive page of all posts
make_date_index "*/*/*" "Archives" > archive.html

# Run all user specified plugins
# Only load plugins from the execution path
# Do not run arbitrary files in the web directory
for plugin in ${plugins}; do
	[ ${1-""} = "-v" ] && echo "Running plugin: ${plugin}"
	. ${0%/*}/plugins/${plugin}.sh
done
